name: Fitbit Build SDK 6.2
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16' # SDK 6.2 i√ßin Node 16 daha iyidir
      - name: Install
        run: |
          npm install --ignore-scripts --legacy-peer-deps
      - name: Build
        run: npx fitbit-build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Versa4-Gercek-Build
          path: build/*.fba
