name: Fitbit Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Fitbit SDK
        run: |
          npm install --ignore-scripts
          # Cihaz tanımlarını içeren paketi özellikle ekliyoruz
          npm install @fitbit/sdk-build-targets @fitbit/sdk-cli @fitbit/sdk --save-dev --ignore-scripts
          
      - name: Build App
        run: npx fitbit-build
        
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Versa4-Not-Uygulamasi
          path: build/*.fba
