name: Fitbit Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16' # SDK 5.0 ile en uyumlu sürüm
          
      - name: Install
        run: |
          npm install --ignore-scripts
          npm install @fitbit/sdk-cli --save-dev --ignore-scripts
          
      - name: Build
        run: npx fitbit-build
        
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Versa4-Uygulamasi
          path: build/*.fba
