name: Fitbit Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install
        run: |
          npm install --ignore-scripts
          npm install @fitbit/sdk-cli --save-dev --ignore-scripts
      - name: Build
        run: npx fitbit-build
      - name: Manipulate Manifest for Gallery
        run: |
          cd build
          # .fba dosyasını aç
          unzip *.fba -d tmp_fba
          # Manifest dosyasında 'atlas' olan hedefi 'hera' olarak değiştiriyoruz
          # Bu sayede Gallery dosyayı Versa 4 dosyası olarak görecek
          sed -i 's/"atlas"/"hera"/g' tmp_fba/manifest.json
          # Tekrar paketle
          cd tmp_fba
          zip -r ../Versa4_Final_App.fba .
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Versa4-Son-Paket
          path: build/Versa4_Final_App.fba
