name: Fitbit Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # SDK 6.0 i√ßin en iyisi
      - name: Install
        run: |
          npm install --ignore-scripts
          # Paketleri tek tek ve zorlayarak kuruyoruz
          npm install @fitbit/sdk-cli@1.7.3 --save-dev --ignore-scripts
          npm install @fitbit/sdk-build-targets@1.2.1 --save-dev --ignore-scripts
      - name: Build
        run: npx fitbit-build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Versa4-Not-Uygulamasi
          path: build/*.fba
