name: Fitbit Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install
        run: |
          npm install --ignore-scripts
          npm install @fitbit/sdk-cli --save-dev --ignore-scripts
      - name: Build
        run: npx fitbit-build
      - name: Patch for Versa 4
        run: |
          cd build
          unzip *.fba -d tmp_fba
          # Daha agresif bir degisim yapalim
          sed -i 's/atlas/hera/g' tmp_fba/manifest.json
          cd tmp_fba
          zip -r ../Versa4_Final.fba .
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Versa4-Son-Deneme
          path: build/Versa4_Final.fba
